name: Prevent Direct Push to Master

on:
  push:
    branches:
      - master

jobs:
  block-master-push:
    runs-on: ubuntu-latest
    steps:
      - name: Block Push
        run: |
          echo "🚫 Direct pushes to 'master' are not allowed. Use a pull request instead."
          exit 1
